# Generated by Django 3.0.7 on 2021-01-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.TextField()),
                ('dimensions', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cin', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('bien_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerer.Bien')),
                ('type_maison', models.CharField(max_length=100)),
                ('nbre_chambre', models.IntegerField()),
                ('nbre_sallon', models.IntegerField()),
                ('nbre_douche', models.IntegerField()),
                ('nbre_garage', models.IntegerField()),
                ('nbre_cuisine', models.IntegerField()),
                ('autre_detail', models.TextField(blank=True)),
            ],
            bases=('gerer.bien',),
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('bien_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerer.Bien')),
                ('description', models.TextField(blank=True)),
            ],
            bases=('gerer.bien',),
        ),
    ]
