# Generated by Django 3.0.7 on 2021-01-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='image',
            field=models.ImageField(blank=True, upload_to='bien/image'),
        ),
    ]
