# Generated by Django 3.0.7 on 2021-01-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerer', '0002_bien_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='gerer.Utilisateur'),
            preserve_default=False,
        ),
    ]
