# Generated by Django 3.0.7 on 2021-01-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerer', '0004_terrain_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='status',
            field=models.CharField(default='a_louer', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terrain',
            name='status',
            field=models.CharField(default='a_louer', max_length=10),
            preserve_default=False,
        ),
    ]
