# Generated by Django 3.0.7 on 2021-01-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerer', '0005_auto_20210121_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='terrain',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
