# Generated by Django 3.0.7 on 2021-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerer', '0008_auto_20210121_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('nbre_vente', models.IntegerField()),
                ('profil', models.ImageField(blank=True, upload_to='agent')),
            ],
        ),
    ]
